# Generated by Django 5.2.4 on 2025-08-14 19:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaRestrictiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Lista')),
                ('tipo_lista', models.CharField(choices=[('ofac', 'OFAC (Office of Foreign Assets Control)'), ('onu', 'Lista de Sanciones de la ONU'), ('ue', 'Lista de Sanciones de la Unión Europea'), ('clinton', 'Lista Clinton'), ('interpol', 'Lista de Interpol'), ('policia_nacional', 'Policía Nacional'), ('contraloria', 'Contraloría General'), ('procuraduria', 'Procuraduría General'), ('otras', 'Otras listas')], max_length=20, verbose_name='Tipo de Lista')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('url_fuente', models.URLField(blank=True, null=True, verbose_name='URL de la fuente')),
                ('activa', models.BooleanField(default=True, verbose_name='Lista Activa')),
                ('fecha_ultima_actualizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de última actualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Lista Restrictiva',
                'verbose_name_plural': 'Listas Restrictivas',
                'ordering': ['tipo_lista', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la configuración')),
                ('umbral_similitud', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5, verbose_name='Umbral de similitud (%)')),
                ('validacion_automatica', models.BooleanField(default=True, verbose_name='Validación automática activada')),
                ('notificar_coincidencias', models.BooleanField(default=True, verbose_name='Notificar coincidencias por email')),
                ('activa', models.BooleanField(default=True, verbose_name='Configuración activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('listas_activas', models.ManyToManyField(to='validations.listarestrictiva', verbose_name='Listas activas para validación')),
            ],
            options={
                'verbose_name': 'Configuración de Validación',
                'verbose_name_plural': 'Configuraciones de Validación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidacionTercero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('aprobado', 'Aprobado - Sin coincidencias'), ('alerta', 'Alerta - Posibles coincidencias'), ('rechazado', 'Rechazado - Coincidencia confirmada')], default='pendiente', max_length=15, verbose_name='Estado de Validación')),
                ('fecha_validacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Validación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('total_listas_consultadas', models.PositiveIntegerField(default=0, verbose_name='Total de listas consultadas')),
                ('total_coincidencias', models.PositiveIntegerField(default=0, verbose_name='Total de coincidencias encontradas')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='terceros.tercero', verbose_name='Tercero')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Validación de Tercero',
                'verbose_name_plural': 'Validaciones de Terceros',
                'ordering': ['-fecha_validacion'],
            },
        ),
        migrations.CreateModel(
            name='CoincidenciaLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_encontrado', models.CharField(max_length=255, verbose_name='Nombre encontrado en la lista')),
                ('documento_encontrado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento encontrado')),
                ('nivel_coincidencia', models.CharField(choices=[('exacta', 'Coincidencia Exacta'), ('alta', 'Coincidencia Alta'), ('media', 'Coincidencia Media'), ('baja', 'Coincidencia Baja')], max_length=10, verbose_name='Nivel de Coincidencia')),
                ('porcentaje_similitud', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de Similitud')),
                ('detalles_adicionales', models.JSONField(blank=True, default=dict, verbose_name='Detalles adicionales de la coincidencia')),
                ('revisado', models.BooleanField(default=False, verbose_name='Revisado por usuario')),
                ('es_falso_positivo', models.BooleanField(default=False, verbose_name='Marcado como falso positivo')),
                ('observaciones_revision', models.TextField(blank=True, null=True, verbose_name='Observaciones de la revisión')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de detección')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('lista_restrictiva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='validations.listarestrictiva', verbose_name='Lista Restrictiva')),
                ('validacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coincidencias', to='validations.validaciontercero', verbose_name='Validación')),
            ],
            options={
                'verbose_name': 'Coincidencia en Lista',
                'verbose_name_plural': 'Coincidencias en Listas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='validaciontercero',
            index=models.Index(fields=['estado'], name='validations_estado_b71dab_idx'),
        ),
        migrations.AddIndex(
            model_name='validaciontercero',
            index=models.Index(fields=['fecha_validacion'], name='validations_fecha_v_ac14de_idx'),
        ),
        migrations.AddIndex(
            model_name='coincidencialista',
            index=models.Index(fields=['nivel_coincidencia'], name='validations_nivel_c_b2d03b_idx'),
        ),
        migrations.AddIndex(
            model_name='coincidencialista',
            index=models.Index(fields=['revisado'], name='validations_revisad_e0a139_idx'),
        ),
    ]
