# Generated by Django 5.2.4 on 2025-08-14 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_metricas_generales', models.BooleanField(default=True, verbose_name='Mostrar métricas generales')),
                ('mostrar_grafico_terceros', models.BooleanField(default=True, verbose_name='Mostrar gráfico de terceros')),
                ('mostrar_alertas_validacion', models.BooleanField(default=True, verbose_name='Mostrar alertas de validación')),
                ('mostrar_documentos_pendientes', models.BooleanField(default=True, verbose_name='Mostrar documentos pendientes')),
                ('mostrar_ultimos_terceros', models.BooleanField(default=True, verbose_name='Mostrar últimos terceros')),
                ('periodo_metricas', models.CharField(choices=[('7d', 'Últimos 7 días'), ('30d', 'Últimos 30 días'), ('90d', 'Últimos 90 días'), ('1y', 'Último año')], default='30d', max_length=10, verbose_name='Período para métricas')),
                ('max_terceros_recientes', models.PositiveIntegerField(default=10, verbose_name='Máximo terceros recientes a mostrar')),
                ('max_alertas', models.PositiveIntegerField(default=5, verbose_name='Máximo alertas a mostrar')),
                ('auto_refresh', models.BooleanField(default=True, verbose_name='Actualización automática')),
                ('refresh_interval', models.PositiveIntegerField(default=300, verbose_name='Intervalo de actualización (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_dashboard', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Configuración del Dashboard',
                'verbose_name_plural': 'Configuraciones del Dashboard',
            },
        ),
        migrations.CreateModel(
            name='MetricaTerceros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la métrica')),
                ('total_terceros', models.PositiveIntegerField(default=0, verbose_name='Total de terceros')),
                ('terceros_pendientes', models.PositiveIntegerField(default=0, verbose_name='Terceros pendientes de aprobación')),
                ('terceros_aprobados', models.PositiveIntegerField(default=0, verbose_name='Terceros aprobados')),
                ('terceros_rechazados', models.PositiveIntegerField(default=0, verbose_name='Terceros rechazados')),
                ('terceros_en_revision', models.PositiveIntegerField(default=0, verbose_name='Terceros en revisión')),
                ('personas_naturales', models.PositiveIntegerField(default=0, verbose_name='Personas naturales')),
                ('personas_juridicas', models.PositiveIntegerField(default=0, verbose_name='Personas jurídicas')),
                ('validaciones_pendientes', models.PositiveIntegerField(default=0, verbose_name='Validaciones pendientes')),
                ('validaciones_con_alerta', models.PositiveIntegerField(default=0, verbose_name='Validaciones con alerta')),
                ('documentos_pendientes', models.PositiveIntegerField(default=0, verbose_name='Documentos pendientes de validación')),
                ('documentos_rechazados', models.PositiveIntegerField(default=0, verbose_name='Documentos rechazados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Métrica de Terceros',
                'verbose_name_plural': 'Métricas de Terceros',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='dashboard_m_fecha_874938_idx')],
                'unique_together': {('fecha',)},
            },
        ),
        migrations.CreateModel(
            name='AlertaDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la alerta')),
                ('mensaje', models.TextField(verbose_name='Mensaje de la alerta')),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('danger', 'Peligro'), ('success', 'Éxito')], default='info', max_length=10, verbose_name='Tipo de alerta')),
                ('categoria', models.CharField(choices=[('terceros', 'Terceros'), ('documentos', 'Documentos'), ('validaciones', 'Validaciones'), ('sistema', 'Sistema')], max_length=15, verbose_name='Categoría')),
                ('mostrar_a_rol', models.CharField(blank=True, choices=[('procesos', 'Procesos'), ('comercial', 'Comercial'), ('gestion_humana', 'Gestión Humana')], max_length=20, null=True, verbose_name='Mostrar solo a rol específico')),
                ('activa', models.BooleanField(default=True, verbose_name='Alerta activa')),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('url_accion', models.URLField(blank=True, null=True, verbose_name='URL de acción')),
                ('texto_accion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto del botón de acción')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('mostrar_a_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mostrar solo a usuario específico')),
            ],
            options={
                'verbose_name': 'Alerta del Dashboard',
                'verbose_name_plural': 'Alertas del Dashboard',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activa', 'categoria'], name='dashboard_a_activa_501ede_idx'), models.Index(fields=['mostrar_a_rol'], name='dashboard_a_mostrar_2b3ce9_idx'), models.Index(fields=['fecha_expiracion'], name='dashboard_a_fecha_e_8c4748_idx')],
            },
        ),
    ]
