# Generated by Django 5.2.4 on 2025-08-14 19:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('procesos', 'Procesos'), ('comercial', 'Comercial'), ('gestion_humana', 'Gestión Humana')], default='procesos', max_length=20, verbose_name='Rol')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('cargo', models.CharField(blank=True, help_text='Ej: Analista, Coordinador', max_length=100, null=True, verbose_name='Cargo')),
                ('area', models.CharField(blank=True, help_text='Ej: Recursos Humanos, Contabilidad', max_length=100, null=True, verbose_name='Área')),
                ('fecha_contratacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación')),
                ('tipo_documento', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PASAPORTE', 'Pasaporte'), ('NIT', 'NIT')], max_length=20, null=True, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(blank=True, help_text='Número de identificación', max_length=20, null=True, verbose_name='Número de Documento')),
                ('direccion', models.TextField(blank=True, help_text='Dirección completa', null=True, verbose_name='Dirección')),
                ('estado_empleado', models.CharField(choices=[('activo', 'Activo - Empleado habilitado'), ('inactivo', 'Inactivo - Empleado inhabilitado'), ('suspendido', 'Suspendido - Empleado temporalmente inhabilitado'), ('vacaciones', 'En Vacaciones'), ('licencia', 'En Licencia')], default='activo', max_length=20, verbose_name='Estado del Empleado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
