# Generated by Django 5.2.4 on 2025-08-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_cargo_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.CharField(blank=True, help_text='Ej: Analista, Coordinador', max_length=100, null=True, verbose_name='Cargo'),
        ),
    ]
