# Generated by Django 5.2.5 on 2025-08-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('procesos', 'Procesos'), ('comercial', 'Comercial'), ('gestion_humana', 'Gestión Humana'), ('oficial_cumplimiento', 'Oficial de Cumplimiento'), ('administrador', 'Administrador')], default='procesos', max_length=20, verbose_name='Rol'),
        ),
    ]
