# Generated by Django 5.2.4 on 2025-09-25 16:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('creada', 'Creada'), ('asignada_administrador', 'Asignada a Administrador'), ('en_revision', 'En Revisión'), ('devuelta_gh', 'Devuelta a Gestión Humana'), ('asignada_procesos', 'Asignada a Procesos'), ('completada', 'Completada'), ('finalizada', 'Finalizada')], default='creada', help_text='Estado actual de la solicitud', max_length=50, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización')),
                ('observaciones_generales', models.TextField(blank=True, help_text='Observaciones opcionales sobre la solicitud', null=True, verbose_name='Observaciones generales')),
                ('asignada_a', models.ForeignKey(blank=True, help_text='Usuario asignado actualmente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignada a')),
                ('creada_por', models.ForeignKey(help_text='Usuario que creó la solicitud', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(help_text='Orden de la persona dentro de la solicitud', verbose_name='Orden')),
                ('nombres_apellidos', models.CharField(help_text='Nombres y apellidos completos', max_length=255, verbose_name='Nombres y apellidos')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], max_length=10, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(help_text='Número del documento de identidad', max_length=50, verbose_name='Número de documento')),
                ('antecedentes', models.TextField(blank=True, help_text='Información de antecedentes (rellenado por Admin/Procesos)', null=True, verbose_name='Antecedentes')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la persona', null=True, verbose_name='Observaciones')),
                ('riesgo', models.CharField(blank=True, choices=[('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo')], help_text='Nivel de riesgo asignado por Admin/Procesos', max_length=10, null=True, verbose_name='Nivel de riesgo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='usuarios_consultas.solicitud', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['solicitud', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del cambio')),
                ('accion', models.CharField(help_text='Descripción de la acción realizada', max_length=255, verbose_name='Acción')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales del cambio', null=True, verbose_name='Descripción')),
                ('estado_anterior', models.CharField(blank=True, choices=[('creada', 'Creada'), ('asignada_administrador', 'Asignada a Administrador'), ('en_revision', 'En Revisión'), ('devuelta_gh', 'Devuelta a Gestión Humana'), ('asignada_procesos', 'Asignada a Procesos'), ('completada', 'Completada'), ('finalizada', 'Finalizada')], max_length=50, null=True, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(blank=True, choices=[('creada', 'Creada'), ('asignada_administrador', 'Asignada a Administrador'), ('en_revision', 'En Revisión'), ('devuelta_gh', 'Devuelta a Gestión Humana'), ('asignada_procesos', 'Asignada a Procesos'), ('completada', 'Completada'), ('finalizada', 'Finalizada')], max_length=50, null=True, verbose_name='Estado nuevo')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó el cambio', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='usuarios_consultas.solicitud', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Historial de Cambio',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['estado'], name='idx_solicitud_estado'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['creada_por'], name='idx_solicitud_creada_por'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['asignada_a'], name='idx_solicitud_asignada_a'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['fecha_creacion'], name='idx_solicitud_fecha_creacion'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['solicitud'], name='idx_persona_solicitud'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['tipo_documento', 'numero_documento'], name='idx_persona_documento'),
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('solicitud', 'orden')},
        ),
        migrations.AddIndex(
            model_name='historialcambio',
            index=models.Index(fields=['solicitud'], name='idx_historial_solicitud'),
        ),
        migrations.AddIndex(
            model_name='historialcambio',
            index=models.Index(fields=['fecha_cambio'], name='idx_historial_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialcambio',
            index=models.Index(fields=['usuario'], name='idx_historial_usuario'),
        ),
    ]
