# Generated by Django 5.2.4 on 2025-09-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcambio',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('creada', 'Creada'), ('asignada_administrador', 'Asignada a Administrador'), ('en_revision_administrador', 'En revisión por Administrador'), ('asignada_procesos', 'Asignada a Procesos'), ('en_revision_procesos', 'En revisión por Procesos'), ('devuelta_gh', 'Devuelta a GH'), ('finalizada', 'Finalizada')], max_length=50, null=True, verbose_name='Estado anterior'),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='estado_nuevo',
            field=models.CharField(blank=True, choices=[('creada', 'Creada'), ('asignada_administrador', 'Asignada a Administrador'), ('en_revision_administrador', 'En revisión por Administrador'), ('asignada_procesos', 'Asignada a Procesos'), ('en_revision_procesos', 'En revisión por Procesos'), ('devuelta_gh', 'Devuelta a GH'), ('finalizada', 'Finalizada')], max_length=50, null=True, verbose_name='Estado nuevo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('creada', 'Creada'), ('asignada_administrador', 'Asignada a Administrador'), ('en_revision_administrador', 'En revisión por Administrador'), ('asignada_procesos', 'Asignada a Procesos'), ('en_revision_procesos', 'En revisión por Procesos'), ('devuelta_gh', 'Devuelta a GH'), ('finalizada', 'Finalizada')], default='creada', help_text='Estado actual de la solicitud', max_length=50, verbose_name='Estado'),
        ),
    ]
