# Generated by Django 5.2.4 on 2025-09-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_consultas', '0002_actualizar_estados_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='riesgo',
            field=models.CharField(blank=True, choices=[('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo'), ('SIN_ANTECEDENTES', 'Sin Antecedentes')], help_text='Nivel de riesgo asignado por Admin/Procesos', max_length=20, null=True, verbose_name='Nivel de riesgo'),
        ),
    ]
