# Generated by Django 5.2.4 on 2025-08-14 19:46

import django.core.validators
import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Documento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('es_obligatorio', models.BooleanField(default=True, verbose_name='Es Obligatorio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de presentación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_tercero_documentos', to='terceros.tercero', verbose_name='Tercero')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoTercero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to=documents.models.upload_documento_tercero, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])], verbose_name='Archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre Original del Archivo')),
                ('tamano_archivo', models.PositiveIntegerField(verbose_name='Tamaño del Archivo (bytes)')),
                ('estado_validacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('requiere_ajustes', 'Requiere Ajustes')], default='pendiente', max_length=20, verbose_name='Estado de Validación')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación')),
                ('observaciones_validacion', models.TextField(blank=True, null=True, verbose_name='Observaciones de Validación')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='terceros.tercero', verbose_name='Tercero')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.tipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento de Tercero',
                'verbose_name_plural': 'Documentos de Terceros',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('requiere_ajustes', 'Requiere Ajustes')], max_length=20, null=True, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('requiere_ajustes', 'Requiere Ajustes')], max_length=20, verbose_name='Estado Nuevo')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='documents.documentotercero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Documento',
                'verbose_name_plural': 'Historiales de Documentos',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='documentotercero',
            index=models.Index(fields=['estado_validacion'], name='documents_d_estado__821d00_idx'),
        ),
        migrations.AddIndex(
            model_name='documentotercero',
            index=models.Index(fields=['fecha_subida'], name='documents_d_fecha_s_a947f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentotercero',
            unique_together={('tercero', 'tipo_documento')},
        ),
    ]
