# Generated by Django 5.2.4 on 2025-09-10 15:21

import django.db.models.deletion
import stradata_consulta.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros', '0022_remove_tercero_fecha_asignacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrataDataDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(help_text='Nombre original del archivo', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del documento', null=True)),
                ('archivo', models.FileField(help_text='Archivo del documento Stradata', upload_to=stradata_consulta.models.stradata_documento_upload_path)),
                ('tipo_consulta', models.CharField(default='Búsqueda Unificada', help_text='Tipo de consulta Stradata', max_length=100)),
                ('tamaño_archivo', models.BigIntegerField(help_text='Tamaño del archivo en bytes')),
                ('tipo_mime', models.CharField(help_text='Tipo MIME del archivo', max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_stradata_subidos', to=settings.AUTH_USER_MODEL)),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_stradata', to='terceros.tercero')),
            ],
            options={
                'verbose_name': 'Documento Stradata',
                'verbose_name_plural': 'Documentos Stradata',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
