# Generated by Django 5.2.4 on 2025-08-14 19:46

import django.core.validators
import django.db.models.deletion
import terceros.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Documento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('es_obligatorio', models.BooleanField(default=True, verbose_name='Es Obligatorio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de presentación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('NIT', 'NIT')], max_length=3, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento solo puede contener números, letras y guiones.', regex='^[0-9A-Za-z\\-]+$')], verbose_name='Número de Documento')),
                ('tipo_persona', models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], max_length=10, verbose_name='Tipo de Persona')),
                ('nombres', models.CharField(help_text='Para personas naturales: nombres completos. Para jurídicas: razón social', max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, help_text='Solo para personas naturales', max_length=150, null=True, verbose_name='Apellidos')),
                ('razon_social', models.CharField(blank=True, help_text='Solo para personas jurídicas', max_length=255, null=True, verbose_name='Razón Social')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido.', regex='^\\+?[0-9\\s\\-\\(\\)]{7,20}$')], verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('estado_aprobacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('requiere_ajustes', 'Requiere Ajustes')], default='pendiente', max_length=20, verbose_name='Estado de Aprobación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terceros_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoTercero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to=terceros.models.upload_documento_tercero, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])], verbose_name='Archivo')),
                ('estado_validacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('requiere_ajustes', 'Requiere Ajustes')], default='pendiente', max_length=20, verbose_name='Estado de Validación')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación')),
                ('observaciones_validacion', models.TextField(blank=True, null=True, verbose_name='Observaciones de Validación')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_subidos_tercero', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_validados_tercero', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_tercero_relacionados', to='terceros.tercero', verbose_name='Tercero')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terceros.tipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento de Tercero',
                'verbose_name_plural': 'Documentos de Terceros',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AddIndex(
            model_name='tercero',
            index=models.Index(fields=['numero_documento'], name='terceros_te_numero__ee76bf_idx'),
        ),
        migrations.AddIndex(
            model_name='tercero',
            index=models.Index(fields=['estado_aprobacion'], name='terceros_te_estado__ff73d9_idx'),
        ),
        migrations.AddIndex(
            model_name='tercero',
            index=models.Index(fields=['created_at'], name='terceros_te_created_25c62c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentotercero',
            index=models.Index(fields=['estado_validacion'], name='terceros_do_estado__616c50_idx'),
        ),
        migrations.AddIndex(
            model_name='documentotercero',
            index=models.Index(fields=['fecha_subida'], name='terceros_do_fecha_s_a6b6cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentotercero',
            unique_together={('tercero', 'tipo_documento')},
        ),
    ]
