# Generated by Django 5.2.4 on 2025-08-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentotercero',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Original del Archivo'),
        ),
    ]
