# Generated by Django 5.2.4 on 2025-08-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_documentotercero_nombre_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentotercero',
            name='nombre_original',
        ),
    ]
