# Generated by Django 5.2.4 on 2025-08-22 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0004_documentotercero_nombre_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='constituyePatrimoniosAutonomos',
            field=models.BooleanField(blank=True, help_text='Declaración obligatoria SARLAFT', null=True, verbose_name='Constituye Patrimonios Autónomos (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='declaracionTransparencia',
            field=models.BooleanField(blank=True, help_text='Declaración obligatoria SARLAFT', null=True, verbose_name='Declaración de Transparencia (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='detallesPEP',
            field=models.TextField(blank=True, help_text='Detalles si es persona expuesta políticamente', verbose_name='Detalles PEP (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='fuentesFondos',
            field=models.JSONField(blank=True, default=list, help_text='Array con opciones múltiples de fuentes', verbose_name='Fuentes de Fondos (Frontend)'),
        ),
        migrations.CreateModel(
            name='InformacionPEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo de la persona PEP', max_length=255, verbose_name='Nombre Completo')),
                ('tipo', models.CharField(choices=[('funcionario', 'Funcionario Público'), ('familiar', 'Familiar de Funcionario'), ('colaborador', 'Colaborador Cercano'), ('otro', 'Otro')], help_text='Tipo de relación con poder político', max_length=50, verbose_name='Tipo de PEP')),
                ('numero_identificacion', models.CharField(help_text='Documento de identidad de la persona PEP', max_length=50, verbose_name='Número de Identificación')),
                ('patrimonio_fiducia', models.BooleanField(default=False, help_text='¿Tiene patrimonio manejado en fiducia?', verbose_name='Patrimonio en Fiducia')),
                ('relaciones_comerciales', models.BooleanField(default=False, help_text='¿Mantiene relaciones comerciales activas?', verbose_name='Relaciones Comerciales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_pep', to='terceros.tercero', verbose_name='Tercero')),
            ],
            options={
                'verbose_name': 'Información PEP',
                'verbose_name_plural': 'Información PEP',
                'indexes': [models.Index(fields=['tercero', 'tipo'], name='terceros_in_tercero_78e242_idx'), models.Index(fields=['numero_identificacion'], name='terceros_in_numero__d6a910_idx')],
            },
        ),
    ]
