# Generated by Django 5.2.4 on 2025-08-25 13:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import terceros.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0005_agregar_campos_sarlaft_pep_criticos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte'), ('NIT', 'NIT'), ('RUT', 'RUT')], max_length=5)),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('porcentaje_participacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accionista',
                'verbose_name_plural': 'Accionistas',
            },
        ),
        migrations.CreateModel(
            name='ComposicionAccionaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_razon_social', models.CharField(max_length=200)),
                ('tipo_identificacion', models.CharField(choices=[('cedula_ciudadania', 'Cédula de Ciudadanía'), ('cedula_extranjeria', 'Cédula de Extranjería'), ('nit', 'NIT'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], max_length=50)),
                ('numero_identificacion', models.CharField(max_length=50)),
                ('porcentaje_participacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Composición Accionaria',
                'verbose_name_plural': 'Composiciones Accionarias',
            },
        ),
        migrations.CreateModel(
            name='InformacionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('costos_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('otros_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('activos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pasivos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('patrimonio', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('detalle_otros_ingresos', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Información Financiera',
                'verbose_name_plural': 'Informaciones Financieras',
            },
        ),
        migrations.CreateModel(
            name='RepresentanteLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('tipo_identificacion', models.CharField(choices=[('cedula_ciudadania', 'Cédula de Ciudadanía'), ('cedula_extranjeria', 'Cédula de Extranjería'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], max_length=50)),
                ('numero_identificacion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Representante Legal',
                'verbose_name_plural': 'Representantes Legales',
            },
        ),
        migrations.AlterModelOptions(
            name='documentotercero',
            options={'verbose_name': 'Documento de Tercero', 'verbose_name_plural': 'Documentos de Terceros'},
        ),
        migrations.RemoveIndex(
            model_name='documentotercero',
            name='terceros_do_estado__616c50_idx',
        ),
        migrations.AlterUniqueTogether(
            name='documentotercero',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documentotercero',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='documentotercero',
            name='es_vigente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentotercero',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentotercero',
            name='tamano_archivo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentotercero',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='accionistas_frontend',
            field=models.JSONField(blank=True, default=list, verbose_name='Accionistas Frontend'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='actividad_economica_principal',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='tercero',
            name='activos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Activos'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='asignado_a',
            field=models.ForeignKey(blank=True, help_text='Comercial asignado por procesos para gestión del tercero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='asignado_a_procesos',
            field=models.ForeignKey(blank=True, help_text='Usuario de procesos asignado automáticamente para primera revisión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_asignados_procesos', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a Procesos'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='auto_retenedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tercero',
            name='autorizacionTratamientoDatos',
            field=models.BooleanField(blank=True, null=True, verbose_name='Autorización Tratamiento Datos (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='autorizacion_tratamiento_datos',
            field=models.BooleanField(default=False, help_text='Obligatorio para procesar la información', verbose_name='Autorización Tratamiento de Datos Personales'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tercero',
            name='codigo_ciiu',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='tercero',
            name='condicionesExentoRenta',
            field=models.TextField(blank=True, verbose_name='Condiciones Exento Renta (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='condiciones_exencion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='condiciones_exento_renta',
            field=models.TextField(blank=True, verbose_name='Condiciones de Exención de Renta'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='correoFacturacion',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Correo Facturación (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='correo_facturacion_electronica',
            field=models.EmailField(default='facturacion@tercero.com', help_text='Obligatorio para todos los terceros', max_length=254, verbose_name='Correo para Facturación Electrónica'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='costosGastos',
            field=models.CharField(blank=True, max_length=50, verbose_name='Costos y Gastos (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='costos_gastos_mensuales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Costos y Gastos Mensuales'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='detalleOtrosIngresos',
            field=models.TextField(blank=True, verbose_name='Detalle Otros Ingresos (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='detalle_operaciones_extranjera',
            field=models.TextField(blank=True, default='No, solo operaciones en pesos colombianos'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='detalle_otros_ingresos',
            field=models.TextField(blank=True, verbose_name='Detalle de Otros Ingresos'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='digito_verificacion',
            field=models.CharField(blank=True, help_text='Obligatorio para NIT y RUT', max_length=1, null=True, validators=[django.core.validators.RegexValidator(message='El dígito de verificación debe ser un número.', regex='^[0-9]$')], verbose_name='Dígito de Verificación'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='exentoRenta',
            field=models.BooleanField(blank=True, null=True, verbose_name='Exento Renta (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='exento_impuesto_renta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tercero',
            name='exento_renta',
            field=models.BooleanField(default=False, verbose_name='Exento de Renta'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='fechaResolucionAutorretenedor',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Resolución Autorretenedor (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='fechaResolucionGC',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Resolución GC (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='fecha_asignacion_procesos',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asignación a procesos'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='fecha_resolucion_autorretenedor',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Resolución Autorretenedor'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='fecha_resolucion_gc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='granContribuyente',
            field=models.BooleanField(blank=True, null=True, verbose_name='Gran Contribuyente (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='gran_contribuyente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tercero',
            name='ingresoMensual',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ingreso Mensual (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='ingreso_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ingresos Mensuales'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='manejoAltoEfectivo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Manejo Alto Efectivo (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='manejo_alto_efectivo',
            field=models.BooleanField(default=False, verbose_name='Manejo de Alto Volumen de Efectivo'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='numeroResolucionAutorretenedor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número Resolución Autorretenedor (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='numeroResolucionGC',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número Resolución GC (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='numero_resolucion_autorretenedor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número Resolución Autorretenedor'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='numero_resolucion_gc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tercero',
            name='observaciones_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='operacionesMonedaExtranjera',
            field=models.BooleanField(blank=True, null=True, verbose_name='Operaciones Moneda Extranjera (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='operaciones_moneda_extranjera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tercero',
            name='origenFondos',
            field=models.TextField(blank=True, verbose_name='Origen Fondos (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='origen_fondos',
            field=models.TextField(default='Actividad económica principal', help_text='Descripción del origen de los recursos', verbose_name='Origen de los Fondos'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='otrosIngresos',
            field=models.CharField(blank=True, max_length=50, verbose_name='Otros Ingresos (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='otros_ingresos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Otros Ingresos'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='pais',
            field=models.CharField(default='Colombia', max_length=100),
        ),
        migrations.AddField(
            model_name='tercero',
            name='pasivos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Pasivos'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='patrimonio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Patrimonio'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='personaExpuestaPolitica',
            field=models.BooleanField(blank=True, null=True, verbose_name='Persona Expuesta Política (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='persona_expuesta_politica',
            field=models.BooleanField(default=False, verbose_name='Persona Expuesta Políticamente (PEP)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='representantes',
            field=models.JSONField(blank=True, default=list, verbose_name='Representantes (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='responsableIVA',
            field=models.BooleanField(blank=True, null=True, verbose_name='Responsable IVA (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='responsable_iva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tercero',
            name='tipo_formulario',
            field=models.CharField(choices=[('vinculacion', 'Vinculación'), ('actualizacion', 'Actualización')], default='vinculacion', max_length=20, verbose_name='Tipo de Formulario'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='tiposOperacionesMonedaExtranjera',
            field=models.JSONField(blank=True, default=list, verbose_name='Tipos Operaciones Moneda Extranjera (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='tiposRecursos',
            field=models.JSONField(blank=True, default=list, verbose_name='Tipos Recursos (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='tipos_operaciones_extranjera',
            field=models.JSONField(blank=True, default=list, help_text='Array de: exportacion, importacion, etc.', verbose_name='Tipos de Operaciones en Moneda Extranjera'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='tipos_recursos',
            field=models.JSONField(blank=True, default=list, help_text='Array de: efectivo, transferencia, etc. Máximo 2 tipos', verbose_name='Tipos de Recursos'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='totalIngresos',
            field=models.CharField(blank=True, max_length=50, verbose_name='Total Ingresos (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='total_ingresos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Ingresos'),
        ),
        migrations.AlterField(
            model_name='documentotercero',
            name='archivo',
            field=models.FileField(upload_to=terceros.models.upload_documento_tercero),
        ),
        migrations.AlterField(
            model_name='documentotercero',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documentotercero',
            name='nombre_original',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentotercero',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='terceros.tercero'),
        ),
        migrations.AlterField(
            model_name='documentotercero',
            name='tipo_documento',
            field=models.CharField(choices=[('documento_identidad', 'Documento de Identidad'), ('rut', 'RUT'), ('certificacion_comercial', 'Certificación Comercial'), ('certificacion_bancaria', 'Certificación Bancaria'), ('documento_identidad_representante', 'Documento de Identidad del Representante Legal'), ('certificado_existencia_representacion', 'Certificado de Existencia y Representación'), ('composicion_accionaria_certificada', 'Composición Accionaria Certificada'), ('estados_financieros_comparativos', 'Estados Financieros Comparativos (2 años)'), ('declaracion_renta', 'Declaración de Renta'), ('certificacion_comercial_1', 'Certificación Comercial #1'), ('certificacion_comercial_2', 'Certificación Comercial #2'), ('cedula', 'Cédula'), ('certificado', 'Certificado'), ('otros', 'Otros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='documentotercero',
            index=models.Index(fields=['tercero', 'tipo_documento'], name='terceros_do_tercero_f3de28_idx'),
        ),
        migrations.AddIndex(
            model_name='documentotercero',
            index=models.Index(fields=['es_vigente'], name='terceros_do_es_vige_13e1e7_idx'),
        ),
        migrations.AddField(
            model_name='accionista',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accionistas', to='terceros.tercero'),
        ),
        migrations.AddField(
            model_name='composicionaccionaria',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicion_accionaria', to='terceros.tercero'),
        ),
        migrations.AddField(
            model_name='informacionfinanciera',
            name='tercero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_financiera', to='terceros.tercero'),
        ),
        migrations.AddField(
            model_name='representantelegal',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes_legales', to='terceros.tercero'),
        ),
        migrations.RemoveField(
            model_name='documentotercero',
            name='estado_validacion',
        ),
        migrations.RemoveField(
            model_name='documentotercero',
            name='fecha_validacion',
        ),
        migrations.RemoveField(
            model_name='documentotercero',
            name='observaciones_validacion',
        ),
        migrations.RemoveField(
            model_name='documentotercero',
            name='subido_por',
        ),
        migrations.RemoveField(
            model_name='documentotercero',
            name='validado_por',
        ),
    ]
