# Generated by Django 5.2.4 on 2025-08-25 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0006_accionista_composicionaccionaria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='comercial_asignado',
            field=models.ForeignKey(blank=True, help_text='Comercial elegido por el tercero durante el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_elegidos_por_tercero', to=settings.AUTH_USER_MODEL, verbose_name='Comercial Asignado por el Tercero'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='informacionPEP',
            field=models.JSONField(blank=True, default=list, help_text='Array de objetos con datos de personas expuestas políticamente', verbose_name='Información PEP (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='nombreRazonSocial',
            field=models.CharField(blank=True, help_text='Campo unificado del frontend', max_length=255, verbose_name='Nombre/Razón Social (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='patrimonioFiducia',
            field=models.BooleanField(blank=True, null=True, verbose_name='Patrimonio en Fiducia (Frontend)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='relacionesComerciales',
            field=models.BooleanField(blank=True, null=True, verbose_name='Relaciones Comerciales (Frontend)'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='tipo_persona',
            field=models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica'), ('publica', 'Entidad Pública')], max_length=10, verbose_name='Tipo de Persona'),
        ),
    ]
