# Generated by Django 5.2.5 on 2025-08-26 23:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0007_tercero_comercial_asignado_tercero_informacionpep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadAdministrativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('usuario_creado', 'Usuario Creado'), ('usuario_modificado', 'Usuario Modificado'), ('usuario_desactivado', 'Usuario Desactivado'), ('tercero_reasignado', 'Tercero Reasignado'), ('configuracion_sistema', 'Configuración del Sistema'), ('backup_realizado', 'Backup Realizado'), ('mantenimiento', 'Mantenimiento del Sistema'), ('auditoria', 'Auditoría del Sistema'), ('redistribucion', 'Redistribución de Carga'), ('otros', 'Otros')], max_length=50, verbose_name='Tipo de Actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción de la actividad')),
                ('datos_adicionales', models.JSONField(blank=True, help_text='Información adicional en formato JSON', null=True, verbose_name='Datos adicionales')),
                ('fecha_actividad', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Actividad')),
                ('tercero_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_administrativas', to='terceros.tercero', verbose_name='Tercero Afectado')),
                ('usuario_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_administrativas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('usuario_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Afectado')),
            ],
            options={
                'verbose_name': 'Actividad Administrativa',
                'verbose_name_plural': 'Actividades Administrativas',
                'ordering': ['-fecha_actividad'],
                'indexes': [models.Index(fields=['usuario_administrador', 'fecha_actividad'], name='terceros_ac_usuario_50eb4d_idx'), models.Index(fields=['tipo_actividad', 'fecha_actividad'], name='terceros_ac_tipo_ac_9fc577_idx'), models.Index(fields=['usuario_afectado'], name='terceros_ac_usuario_dd9ade_idx'), models.Index(fields=['tercero_afectado'], name='terceros_ac_tercero_624520_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=50, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(max_length=50, verbose_name='Estado Nuevo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del cambio')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='terceros.tercero', verbose_name='Tercero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que cambió el estado')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historiales de Estado',
                'ordering': ['-fecha_cambio'],
                'indexes': [models.Index(fields=['tercero', 'fecha_cambio'], name='terceros_hi_tercero_d7c75b_idx'), models.Index(fields=['usuario', 'fecha_cambio'], name='terceros_hi_usuario_dbcca5_idx'), models.Index(fields=['estado_nuevo'], name='terceros_hi_estado__0caa46_idx')],
            },
        ),
        migrations.CreateModel(
            name='RevisionCumplimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, help_text='Comentarios y observaciones de la revisión', verbose_name='Observaciones')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado por cumplimiento')),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Riesgo Bajo'), ('medio', 'Riesgo Medio'), ('alto', 'Riesgo Alto')], default='bajo', max_length=20, verbose_name='Nivel de Riesgo')),
                ('requiere_monitoreo', models.BooleanField(default=False, verbose_name='Requiere Monitoreo Continuo')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Revisión')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_cumplimiento', to='terceros.tercero', verbose_name='Tercero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que revisó')),
            ],
            options={
                'verbose_name': 'Revisión de Cumplimiento',
                'verbose_name_plural': 'Revisiones de Cumplimiento',
                'ordering': ['-fecha_revision'],
                'indexes': [models.Index(fields=['tercero', 'fecha_revision'], name='terceros_re_tercero_761d58_idx'), models.Index(fields=['usuario', 'fecha_revision'], name='terceros_re_usuario_984bd6_idx'), models.Index(fields=['nivel_riesgo'], name='terceros_re_nivel_r_2c617d_idx')],
            },
        ),
    ]
