# Generated by Django 5.2.5 on 2025-08-27 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0008_actividadadministrativa_historialestado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='aprobado_por_comercial',
            field=models.ForeignKey(blank=True, help_text='Usuario comercial que realizó la aprobación inicial', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_aprobados_comercial', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por Comercial'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='aprobado_por_procesos',
            field=models.ForeignKey(blank=True, help_text='Usuario de procesos que realizó la aprobación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_aprobados_procesos', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por Procesos'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='asignado_administrador',
            field=models.ForeignKey(blank=True, help_text='Administrador que gestiona la asignación a procesos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_asignados_admin', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a Administrador'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='asignado_cumplimiento',
            field=models.ForeignKey(blank=True, help_text='Oficial de cumplimiento asignado para revisión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_asignados_cumplimiento', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a Cumplimiento'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='fecha_aprobacion_comercial',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación comercial'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='fecha_aprobacion_procesos',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación procesos'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='fecha_asignacion_administrador',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asignación a administrador'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='fecha_asignacion_cumplimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asignación a cumplimiento'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobado_comercial', 'Aprobado por Comercial'), ('pendiente_administrador', 'Pendiente Administrador'), ('asignado_procesos', 'Asignado a Procesos'), ('aprobado_procesos', 'Aprobado por Procesos'), ('enviado_cumplimiento', 'Enviado a Cumplimiento'), ('aprobado_final', 'Aprobado Final'), ('rechazado', 'Rechazado'), ('requiere_ajustes', 'Requiere Ajustes')], default='pendiente', max_length=30, verbose_name='Estado de Aprobación'),
        ),
    ]
