# Generated by Django 5.2.5 on 2025-08-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0009_tercero_aprobado_por_comercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='canal_contacto',
            field=models.CharField(blank=True, choices=[('telefono', 'Teléfono'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('presencial', 'Presencial'), ('web', 'Página Web'), ('referido', 'Referido'), ('otro', 'Otro')], help_text='Canal por el cual se estableció el primer contacto', max_length=50, verbose_name='Canal de Contacto'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='comentarios_aprobacion',
            field=models.TextField(blank=True, help_text='Comentarios específicos durante el proceso de aprobación', null=True, verbose_name='Comentarios de Aprobación'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='fecha_contacto_inicial',
            field=models.DateTimeField(blank=True, help_text='Fecha del primer contacto comercial', null=True, verbose_name='Fecha de Contacto Inicial'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='notas_internas',
            field=models.TextField(blank=True, help_text='Notas internas del equipo comercial', null=True, verbose_name='Notas Internas'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='observaciones_comercial',
            field=models.TextField(blank=True, help_text='Comentarios y observaciones del comercial durante la gestión', null=True, verbose_name='Observaciones del Comercial'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='prioridad_comercial',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', help_text='Prioridad asignada por el comercial', max_length=10, verbose_name='Prioridad Comercial'),
        ),
    ]
