# Generated by Django 5.2.5 on 2025-08-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0010_tercero_canal_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentotercero',
            name='tipo_documento',
            field=models.CharField(choices=[('documento_identidad', 'Documento de Identidad'), ('rut', 'RUT'), ('certificacion_comercial', 'Certificación Comercial'), ('certificacion_bancaria', 'Certificación Bancaria'), ('documento_identidad_representante', 'Documento de Identidad del Representante Legal'), ('certificado_existencia_representacion', 'Certificado de Existencia y Representación'), ('composicion_accionaria_certificada', 'Composición Accionaria Certificada'), ('estados_financieros_comparativos', 'Estados Financieros Comparativos (2 años)'), ('declaracion_renta', 'Declaración de Renta'), ('certificacion_comercial_1', 'Certificación Comercial #1'), ('certificacion_comercial_2', 'Certificación Comercial #2'), ('stradata', 'Documento de Stradata'), ('cedula', 'Cédula'), ('certificado', 'Certificado'), ('otros', 'Otros')], max_length=50),
        ),
    ]
