# Generated by Django 5.2.5 on 2025-08-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0006_backup'),
        ('terceros', '0011_alter_documentotercero_tipo_documento'),
    ]

    operations = [
    ]
