# Generated by Django 5.2.4 on 2025-09-02 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0012_merge_20250828_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionpep',
            name='cargo',
            field=models.CharField(default='No especificado', help_text='Cargo o posición que desempeña la persona PEP', max_length=255, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='informacionpep',
            name='cuentas_financieras_exterior',
            field=models.BooleanField(default=False, help_text='¿Posee o tiene poder sobre cuentas financieras en el exterior?', verbose_name='Cuentas Financieras en el Exterior'),
        ),
        migrations.AddField(
            model_name='informacionpep',
            name='fecha_retiro',
            field=models.DateField(blank=True, help_text='Fecha de retiro del cargo (YYYY-MM-DD)', null=True, verbose_name='Fecha de Retiro'),
        ),
        migrations.AddField(
            model_name='informacionpep',
            name='fecha_vinculacion',
            field=models.DateField(blank=True, help_text='Fecha de inicio en el cargo (YYYY-MM-DD)', null=True, verbose_name='Fecha de Vinculación'),
        ),
        migrations.AddField(
            model_name='informacionpep',
            name='parentesco',
            field=models.CharField(default='No especificado', help_text='Relación de parentesco con el tercero (Cónyuge, Hijo, Padre, Socio, etc.)', max_length=255, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='informacionpep',
            name='nombre',
            field=models.CharField(help_text='Nombres y apellidos completos de la persona PEP', max_length=255, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='informacionpep',
            name='numero_identificacion',
            field=models.CharField(help_text='Número de documento de identidad de la persona PEP', max_length=50, verbose_name='Número de Identificación'),
        ),
        migrations.AlterField(
            model_name='informacionpep',
            name='patrimonio_fiducia',
            field=models.BooleanField(default=False, help_text='CAMPO LEGACY - Será migrado a cuentas_financieras_exterior', verbose_name='Patrimonio en Fiducia (LEGACY)'),
        ),
        migrations.AlterField(
            model_name='informacionpep',
            name='relaciones_comerciales',
            field=models.BooleanField(default=False, help_text='CAMPO LEGACY - Información manejada ahora con cargo y parentesco', verbose_name='Relaciones Comerciales (LEGACY)'),
        ),
        migrations.AlterField(
            model_name='informacionpep',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_pep_nueva', to='terceros.tercero', verbose_name='Tercero'),
        ),
        migrations.AlterField(
            model_name='informacionpep',
            name='tipo',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT'), ('PASAPORTE', 'Pasaporte')], help_text='Tipo de documento de identificación', max_length=15, verbose_name='Tipo de Documento'),
        ),
        migrations.AddIndex(
            model_name='informacionpep',
            index=models.Index(fields=['fecha_vinculacion'], name='terceros_in_fecha_v_9802ab_idx'),
        ),
        migrations.AddIndex(
            model_name='informacionpep',
            index=models.Index(fields=['fecha_retiro'], name='terceros_in_fecha_r_f195ba_idx'),
        ),
    ]
