# Generated by Django 5.2.4 on 2025-09-03 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0013_actualizacion_estructura_pep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='fecha_asignacion_comercial',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asignación a comercial'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='fecha_ultimo_cambio_estado',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha último cambio de estado'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='observaciones_cumplimiento',
            field=models.TextField(blank=True, help_text='Comentarios del oficial de cumplimiento durante revisión SARLAFT', null=True, verbose_name='Observaciones de Cumplimiento'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='observaciones_procesos',
            field=models.TextField(blank=True, help_text='Comentarios de procesos durante la revisión', null=True, verbose_name='Observaciones de Procesos'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='usuario_ultimo_cambio',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó el último cambio de estado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_cambios_estado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario último cambio'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='asignado_a',
            field=models.ForeignKey(blank=True, help_text='Comercial asignado para gestión del tercero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_asignados_comercial', to=settings.AUTH_USER_MODEL, verbose_name='Asignado Comercial'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='asignado_a_procesos',
            field=models.ForeignKey(blank=True, help_text='Usuario de procesos asignado para revisión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_asignados_procesos', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a Procesos'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado_comercial', 'Asignado a Comercial'), ('aprobado_comercial', 'Aprobado por Comercial'), ('rechazado_comercial', 'Rechazado por Comercial'), ('asignado_procesos', 'Asignado a Procesos'), ('aprobado_procesos', 'Aprobado por Procesos'), ('rechazado_procesos', 'Rechazado por Procesos'), ('enviado_cumplimiento', 'Enviado a Cumplimiento'), ('aprobado_cumplimiento', 'Aprobado por Cumplimiento'), ('rechazado_cumplimiento', 'Rechazado por Cumplimiento'), ('aprobado_final', 'Aprobado Final'), ('rechazado_final', 'Rechazado Final'), ('en_revision', 'En Revisión'), ('pendiente_administrador', 'Pendiente Administrador'), ('rechazado', 'Rechazado'), ('requiere_ajustes', 'Requiere Ajustes')], default='pendiente', max_length=30, verbose_name='Estado de Aprobación'),
        ),
    ]
