# Generated by Django 5.2.4 on 2025-09-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0014_workflow_estados_completos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado_comercial', 'Asignado a Comercial'), ('aprobado_comercial', 'Aprobado por Comercial'), ('rechazado_comercial', 'Rechazado por Comercial'), ('asignado_administrador', 'Asignado a Administrador'), ('asignado_procesos', 'Asignado a Procesos'), ('aprobado_procesos', 'Aprobado por Procesos'), ('rechazado_procesos', 'Rechazado por Procesos'), ('enviado_cumplimiento', 'Enviado a Cumplimiento'), ('aprobado_cumplimiento', 'Aprobado por Cumplimiento'), ('rechazado_cumplimiento', 'Rechazado por Cumplimiento'), ('aprobado_final', 'Aprobado Final'), ('rechazado_final', 'Rechazado Final'), ('en_revision', 'En Revisión'), ('pendiente_administrador', 'Pendiente Administrador'), ('rechazado', 'Rechazado'), ('requiere_ajustes', 'Requiere Ajustes')], default='pendiente', max_length=30, verbose_name='Estado de Aprobación'),
        ),
    ]
