# Generated by Django 5.2.4 on 2025-09-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0015_add_asignado_administrador_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='observaciones_administrador',
            field=models.TextField(blank=True, help_text='Comentarios del administrador durante la gestión del tercero', null=True, verbose_name='Observaciones del Administrador'),
        ),
    ]
