# Generated by Django 5.2.4 on 2025-09-03 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0016_add_observaciones_administrador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTercero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('cambio_estado', 'Cambio de Estado'), ('asignacion_comercial', 'Asignación a Comercial'), ('asignacion_procesos', 'Asignación a Procesos'), ('asignacion_cumplimiento', 'Asignación a Cumplimiento'), ('asignacion_administrador', 'Asignación a Administrador'), ('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo'), ('reasignacion', 'Reasignación'), ('observacion', 'Agregó Observación'), ('reset', 'Reset por Administrador')], max_length=25, verbose_name='Tipo de Acción')),
                ('estado_anterior', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado Nuevo')),
                ('departamento', models.CharField(blank=True, help_text='comercial, procesos, cumplimiento, administrador', max_length=20, null=True, verbose_name='Departamento')),
                ('observaciones', models.TextField(blank=True, help_text='Comentarios o notas sobre la acción realizada', null=True, verbose_name='Observaciones')),
                ('metadatos', models.JSONField(blank=True, default=dict, help_text='Información adicional sobre la acción en formato JSON', verbose_name='Metadatos Adicionales')),
                ('fecha_accion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='terceros.tercero', verbose_name='Tercero')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_acciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('usuario_asignado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_asignaciones_anterior', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado Anterior')),
                ('usuario_asignado_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_asignaciones_nuevo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado Nuevo')),
            ],
            options={
                'verbose_name': 'Historial de Tercero',
                'verbose_name_plural': 'Historiales de Terceros',
                'ordering': ['-fecha_accion'],
                'indexes': [models.Index(fields=['tercero', '-fecha_accion'], name='terceros_hi_tercero_6d92a1_idx'), models.Index(fields=['usuario', '-fecha_accion'], name='terceros_hi_usuario_5407cd_idx'), models.Index(fields=['accion', '-fecha_accion'], name='terceros_hi_accion_3c3210_idx'), models.Index(fields=['estado_nuevo', '-fecha_accion'], name='terceros_hi_estado__94ef28_idx')],
            },
        ),
    ]
