# Generated by Django 5.2.4 on 2025-09-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0017_historialtercero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtercero',
            name='accion',
            field=models.CharField(choices=[('creacion', 'Creación'), ('cambio_estado', 'Cambio de Estado'), ('asignacion_comercial', 'Asignación a Comercial'), ('asignacion_procesos', 'Asignación a Procesos'), ('asignacion_cumplimiento', 'Asignación a Cumplimiento'), ('asignacion_administrador', 'Asignación a Administrador'), ('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo'), ('reasignacion', 'Reasignación'), ('observacion', 'Agregó Observación'), ('reset', 'Reset por Administrador')], max_length=100, verbose_name='Tipo de Acción'),
        ),
    ]
