# Generated by Django 5.2.4 on 2025-09-04 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0019_add_new_workflow_states'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialtercero',
            name='rol_asignado_anterior',
            field=models.CharField(blank=True, choices=[('comercial', 'Comercial'), ('procesos', 'Procesos'), ('oficial_cumplimiento', 'Oficial de Cumplimiento'), ('administrador', 'Administrador')], help_text='Rol del usuario asignado antes del cambio', max_length=25, null=True, verbose_name='Rol Asignado Anterior'),
        ),
        migrations.AddField(
            model_name='historialtercero',
            name='rol_asignado_nuevo',
            field=models.CharField(blank=True, choices=[('comercial', 'Comercial'), ('procesos', 'Procesos'), ('oficial_cumplimiento', 'Oficial de Cumplimiento'), ('administrador', 'Administrador')], help_text='Rol del usuario asignado después del cambio', max_length=25, null=True, verbose_name='Rol Asignado Nuevo'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, help_text='Fecha de la última asignación de usuario', null=True, verbose_name='Fecha de Última Asignación'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='rol_asignado',
            field=models.CharField(blank=True, choices=[('comercial', 'Comercial'), ('procesos', 'Procesos'), ('oficial_cumplimiento', 'Oficial de Cumplimiento'), ('administrador', 'Administrador')], help_text='Rol del usuario que actualmente tiene asignado este tercero', max_length=25, null=True, verbose_name='Rol Asignado Actual'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualmente tiene asignado este tercero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_usuario_asignado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado Actual'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='asignado_a',
            field=models.ForeignKey(blank=True, help_text='Campo legacy - usar usuario_asignado + rol_asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_asignados_comercial', to=settings.AUTH_USER_MODEL, verbose_name='Asignado Comercial (Legacy)'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='asignado_a_procesos',
            field=models.ForeignKey(blank=True, help_text='Campo legacy - usar usuario_asignado + rol_asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_asignados_procesos', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a Procesos (Legacy)'),
        ),
    ]
