# Generated by Django 5.2.4 on 2025-09-09 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0020_add_unified_assignment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialtercero',
            name='rol_asignado_anterior',
        ),
        migrations.RemoveField(
            model_name='historialtercero',
            name='rol_asignado_nuevo',
        ),
        migrations.AlterField(
            model_name='historialtercero',
            name='accion',
            field=models.CharField(choices=[('creacion', 'Creación'), ('cambio_estado', 'Cambio de Estado'), ('asignacion_comercial', 'Asignación a Comercial'), ('asignacion_procesos', 'Asignación a Procesos'), ('asignacion_cumplimiento', 'Asignación a Cumplimiento'), ('asignacion_administrador', 'Asignación a Administrador'), ('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo'), ('reasignacion', 'Reasignación'), ('observacion', 'Agregó Observación'), ('reset', 'Reset por Administrador')], max_length=25, verbose_name='Tipo de Acción'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='asignado_a',
            field=models.ForeignKey(blank=True, help_text='Comercial asignado para gestión del tercero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_asignados_comercial', to=settings.AUTH_USER_MODEL, verbose_name='Asignado Comercial'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='asignado_a_procesos',
            field=models.ForeignKey(blank=True, help_text='Usuario de procesos asignado para revisión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_asignados_procesos', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a Procesos'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_espera_correccion', 'En Espera (Corrección)'), ('devuelto_a_comercial', 'Devuelto a Comercial'), ('en_curso_comercial', 'En Curso (Comercial)'), ('en_curso_administrador', 'En Curso (Administrador)'), ('en_curso_procesos', 'En Curso (Procesos)'), ('en_curso_cumplimiento', 'En Curso (Cumplimiento)'), ('asignada_a_administrador', 'Asignada a Administrador'), ('asignada_a_procesos', 'Asignada a Procesos'), ('asignada_a_cumplimiento', 'Asignada a Oficial de Cumplimiento'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=30, verbose_name='Estado de Aprobación'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de la última asignación', null=True, verbose_name='Fecha de Asignación'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='rol_asignado',
            field=models.CharField(blank=True, choices=[('comercial', 'Comercial'), ('administrador', 'Administrador'), ('procesos', 'Procesos'), ('oficial_cumplimiento', 'Oficial de Cumplimiento'), ('gestion_humana', 'Gestión Humana')], help_text='Rol del usuario actualmente asignado', max_length=25, null=True, verbose_name='Rol Asignado'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, help_text='Usuario actualmente responsable de la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado'),
        ),
    ]
