# Generated by Django 5.2.4 on 2025-09-11 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0022_remove_tercero_fecha_asignacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='fecha_asignacion_actual',
            field=models.DateTimeField(blank=True, help_text='Fecha de la asignación actual', null=True, verbose_name='Fecha de Asignación Actual'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='rol_asignado',
            field=models.CharField(blank=True, choices=[('comercial', 'Comercial'), ('administrador', 'Administrador'), ('procesos', 'Procesos'), ('oficial_cumplimiento', 'Oficial de Cumplimiento')], help_text='Rol del usuario actualmente responsable', max_length=50, null=True, verbose_name='Rol Asignado'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, help_text='Usuario actualmente responsable de la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_asignados_actual', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado Actual'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_espera_correccion', 'En espera (corrección)'), ('en_curso_comercial', 'En curso (Comercial)'), ('en_curso_administrador', 'En curso (Administrador)'), ('en_curso_procesos', 'En curso (Procesos)'), ('en_curso_cumplimiento', 'En curso (Cumplimiento)'), ('asignada_administrador', 'Asignada a Administrador'), ('asignada_procesos', 'Asignada a Procesos'), ('asignada_oficial_cumplimiento', 'Asignada a Oficial de Cumplimiento'), ('devuelto_comercial', 'Devuelto a Comercial'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado'), ('asignado_comercial', 'Asignado a Comercial (Legacy)'), ('aprobado_comercial', 'Aprobado por Comercial (Legacy)'), ('rechazado_comercial', 'Rechazado por Comercial (Legacy)'), ('asignado_administrador', 'Asignado a Administrador (Legacy)'), ('asignado_procesos', 'Asignado a Procesos (Legacy)'), ('aprobado_procesos', 'Aprobado por Procesos (Legacy)'), ('rechazado_procesos', 'Rechazado por Procesos (Legacy)'), ('enviado_cumplimiento', 'Enviado a Cumplimiento (Legacy)'), ('aprobado_cumplimiento', 'Aprobado por Cumplimiento (Legacy)'), ('rechazado_cumplimiento', 'Rechazado por Cumplimiento (Legacy)'), ('aprobado_final', 'Aprobado Final (Legacy)'), ('rechazado_final', 'Rechazado Final (Legacy)'), ('en_revision', 'En Revisión (Legacy)'), ('pendiente_administrador', 'Pendiente Administrador (Legacy)'), ('requiere_ajustes', 'Requiere Ajustes (Legacy)')], default='pendiente', max_length=30, verbose_name='Estado de Aprobación'),
        ),
    ]
