# Generated by Django 5.2.4 on 2025-09-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0023_tercero_fecha_asignacion_actual_tercero_rol_asignado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_espera_correccion', 'En espera (corrección)'), ('en_curso_comercial', 'En curso (Comercial)'), ('en_curso_administrador', 'En curso (Administrador)'), ('en_curso_procesos', 'En curso (Procesos)'), ('en_curso_cumplimiento', 'En curso (Cumplimiento)'), ('asignada_administrador', 'Asignada a Administrador'), ('asignada_procesos', 'Asignada a Procesos'), ('asignada_oficial_cumplimiento', 'Asignada a Oficial de Cumplimiento'), ('devuelto_comercial', 'Devuelto a Comercial'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=30, verbose_name='Estado de Aprobación'),
        ),
    ]
