# Generated by Django 5.2.4 on 2025-09-17 21:22

import terceros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0024_alter_tercero_estado_aprobacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentotercero',
            name='archivo',
            field=models.FileField(upload_to=terceros.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='documentotercero',
            name='tipo_documento',
            field=models.CharField(choices=[('documento_identidad', 'Documento de Identidad'), ('rut', 'RUT'), ('firma', 'Firma'), ('certificacion_comercial', 'Certificación Comercial'), ('certificacion_bancaria', 'Certificación Bancaria'), ('documento_identidad_representante', 'Documento de Identidad del Representante Legal'), ('certificado_existencia_representacion', 'Certificado de Existencia y Representación'), ('composicion_accionaria_certificada', 'Composición Accionaria Certificada'), ('estados_financieros_comparativos', 'Estados Financieros Comparativos (2 años)'), ('declaracion_renta', 'Declaración de Renta'), ('certificacion_comercial_1', 'Certificación Comercial #1'), ('certificacion_comercial_2', 'Certificación Comercial #2'), ('stradata', 'Documento de Stradata'), ('debida_diligencia_formulario', 'Formulario de Debida Diligencia'), ('debida_diligencia_verificacion', 'Lista de Verificación DD'), ('debida_diligencia_bienes', 'Declaración de Bienes'), ('debida_diligencia_vinculacion', 'Carta de No Vinculación'), ('perfil_riesgo_matriz', 'Matriz de Riesgo'), ('perfil_riesgo_evaluacion', 'Evaluación Inicial de Riesgo'), ('perfil_riesgo_actualizacion', 'Actualización de Perfil'), ('perfil_riesgo_calificacion', 'Calificación de Riesgo'), ('soporte_referencias', 'Referencias Comerciales'), ('soporte_financieros', 'Estados Financieros'), ('soporte_certificaciones', 'Certificaciones'), ('soporte_licencias', 'Licencias y Permisos'), ('evaluacion_informe', 'Informe de Evaluación'), ('evaluacion_recomendaciones', 'Recomendaciones'), ('evaluacion_mitigacion', 'Plan de Mitigación'), ('seguimiento_revision', 'Revisión Periódica'), ('seguimiento_actualizacion', 'Actualización de Datos'), ('seguimiento_monitoreo', 'Monitoreo Continuo'), ('debida_diligencia_otro', 'Otro Documento DD'), ('cedula', 'Cédula'), ('certificado', 'Certificado'), ('otros', 'Otros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='correo_facturacion_electronica',
            field=models.EmailField(default='facturacion@empresa.com', help_text='Obligatorio para todos los terceros', max_length=254, verbose_name='Correo para Facturación Electrónica'),
        ),
    ]
