# Generated by Django 5.2.4 on 2025-09-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0025_alter_documentotercero_archivo_and_more'),
    ]

    operations = [
        # Índice compuesto para filtros comunes de paginación
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_terceros_estado_asignado_fecha ON terceros_tercero (estado_aprobacion, asignado_a_id, created_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_terceros_estado_asignado_fecha;"
        ),
        
        # Índice para búsquedas de texto
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_terceros_search_texto ON terceros_tercero (numero_documento, nombres, apellidos);",
            reverse_sql="DROP INDEX IF EXISTS idx_terceros_search_texto;"
        ),
        
        # Índice para filtros de dashboard
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_terceros_dashboard ON terceros_tercero (estado_aprobacion, created_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_terceros_dashboard;"
        ),
        
        # Índice para asignaciones por usuario
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_terceros_asignado ON terceros_tercero (asignado_a_id, fecha_asignacion_actual);",
            reverse_sql="DROP INDEX IF EXISTS idx_terceros_asignado;"
        ),
        
        # Índice para tipo de formulario y persona
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_terceros_tipo ON terceros_tercero (tipo_formulario, tipo_persona, estado_aprobacion);",
            reverse_sql="DROP INDEX IF EXISTS idx_terceros_tipo;"
        ),
    ]
