# Generated by Django 5.2.4 on 2025-09-22 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0026_add_pagination_indexes'),
    ]

    operations = [
        # Agregar campos para estructura jerárquica de accionistas
        migrations.AddField(
            model_name='accionista',
            name='empresa_padre',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Identificación Empresa Padre'),
        ),
        migrations.AddField(
            model_name='accionista',
            name='nivel',
            field=models.IntegerField(default=0, verbose_name='Nivel Jerárquico', help_text='0=principal, 1=sub, etc.'),
        ),
        migrations.AddField(
            model_name='accionista',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accionistas', to='terceros.accionista', verbose_name='Accionista Padre'),
        ),
        # Agregar índices para optimizar consultas
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_accionistas_empresa_padre ON terceros_accionista(empresa_padre);",
            reverse_sql="DROP INDEX IF EXISTS idx_accionistas_empresa_padre;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_accionistas_nivel ON terceros_accionista(nivel);",
            reverse_sql="DROP INDEX IF EXISTS idx_accionistas_nivel;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_accionistas_padre_id ON terceros_accionista(padre_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_accionistas_padre_id;"
        ),
    ]
