# Generated by Django 5.2.4 on 2025-09-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0027_auto_20250922_1047'),
    ]

    operations = [
        # Agregar nuevos campos de contacto separados
        migrations.AddField(
            model_name='tercero',
            name='nombre_persona_contacto',
            field=models.CharField(max_length=255, blank=True, verbose_name='Nombre Persona de Contacto'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='cargo_persona_contacto',
            field=models.CharField(max_length=255, blank=True, verbose_name='Cargo Persona de Contacto'),
        ),
        
        # Agregar nuevos campos para activos virtuales
        migrations.AddField(
            model_name='tercero',
            name='manejo_activos_virtuales',
            field=models.BooleanField(default=False, verbose_name='Maneja Activos Virtuales'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='detalle_activos_virtuales',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle de Activos Virtuales'),
        ),
        
        # Actualizar las opciones de tipo_documento para incluir OTRO
        migrations.AlterField(
            model_name='tercero',
            name='tipo_documento',
            field=models.CharField(
                max_length=5,  # Aumentamos de 3 a 5 para 'OTRO'
                choices=[
                    ('CC', 'Cédula de Ciudadanía'),
                    ('CE', 'Cédula de Extranjería'),
                    ('PA', 'Pasaporte'),
                    ('NIT', 'NIT'),
                    ('OTRO', 'Otro/Exterior'),
                ],
                verbose_name='Tipo de Documento'
            ),
        ),
    ]
