# Generated by Django 5.2.4 on 2025-09-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0028_add_nuevos_campos_contacto_activos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='condiciones_pago_15_dias',
            field=models.BooleanField(default=False, help_text='Permite pago a 15 días', verbose_name='Condiciones de Pago 15 días'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='condiciones_pago_30_dias',
            field=models.BooleanField(default=False, help_text='Permite pago a 30 días', verbose_name='Condiciones de Pago 30 días'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='condiciones_pago_45_dias',
            field=models.BooleanField(default=False, help_text='Permite pago a 45 días', verbose_name='Condiciones de Pago 45 días'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='condiciones_pago_60_dias',
            field=models.BooleanField(default=False, help_text='Permite pago a 60 días', verbose_name='Condiciones de Pago 60 días'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='condiciones_pago_8_dias',
            field=models.BooleanField(default=False, help_text='Permite pago a 8 días', verbose_name='Condiciones de Pago 8 días'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='condiciones_pago_establecidas_por',
            field=models.CharField(blank=True, help_text='Usuario que estableció las condiciones de pago', max_length=100, null=True, verbose_name='Establecidas por'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='condiciones_pago_otro',
            field=models.BooleanField(default=False, help_text='Tiene condiciones de pago especiales', verbose_name='Otras Condiciones de Pago'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='condiciones_pago_otro_valor',
            field=models.CharField(blank=True, help_text='Descripción de las condiciones de pago especiales', max_length=200, null=True, verbose_name='Especificación Otras Condiciones'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='fecha_establecimiento_condiciones',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora cuando se establecieron las condiciones', null=True, verbose_name='Fecha de Establecimiento'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='otras_condiciones_pago',
            field=models.TextField(blank=True, help_text='Observaciones adicionales sobre las condiciones comerciales', null=True, verbose_name='Observaciones Condiciones de Pago'),
        ),
        migrations.AlterField(
            model_name='accionista',
            name='empresa_padre',
            field=models.CharField(blank=True, default='', help_text='Identificación de la empresa padre (para sub-accionistas)', max_length=50, verbose_name='Identificación Empresa Padre'),
        ),
        migrations.AlterField(
            model_name='accionista',
            name='nivel',
            field=models.IntegerField(default=0, help_text='0=principal, 1=sub-accionista, etc.', verbose_name='Nivel Jerárquico'),
        ),
        migrations.AlterField(
            model_name='accionista',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre/Razón Social'),
        ),
        migrations.AlterField(
            model_name='accionista',
            name='numero_identificacion',
            field=models.CharField(max_length=50, verbose_name='Número de Identificación'),
        ),
        migrations.AlterField(
            model_name='accionista',
            name='porcentaje_participacion',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de Participación'),
        ),
        migrations.AlterField(
            model_name='accionista',
            name='tipo_identificacion',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte'), ('NIT', 'NIT'), ('RUT', 'RUT'), ('OTRO', 'Otro')], max_length=5, verbose_name='Tipo de Identificación'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='cargo_persona_contacto',
            field=models.CharField(blank=True, help_text='Cargo o posición de la persona de contacto en la empresa', max_length=255, verbose_name='Cargo Persona de Contacto'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='detalle_activos_virtuales',
            field=models.TextField(blank=True, help_text='Especifique los tipos de activos virtuales que maneja (Bitcoin, Ethereum, NFT, etc.)', null=True, verbose_name='Detalle de Activos Virtuales'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='manejo_activos_virtuales',
            field=models.BooleanField(default=False, help_text='Indica si realiza transacciones con criptomonedas, NFT u otros activos virtuales', verbose_name='Maneja Activos Virtuales'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='nombre_persona_contacto',
            field=models.CharField(blank=True, help_text='Nombre completo de la persona de contacto principal', max_length=255, verbose_name='Nombre Persona de Contacto'),
        ),
        migrations.AlterUniqueTogether(
            name='accionista',
            unique_together={('tercero', 'numero_identificacion', 'nivel')},
        ),
        migrations.AddIndex(
            model_name='accionista',
            index=models.Index(fields=['tercero'], name='terceros_ac_tercero_27207d_idx'),
        ),
        migrations.AddIndex(
            model_name='accionista',
            index=models.Index(fields=['empresa_padre'], name='terceros_ac_empresa_3cdfbe_idx'),
        ),
        migrations.AddIndex(
            model_name='accionista',
            index=models.Index(fields=['padre'], name='terceros_ac_padre_i_c9c448_idx'),
        ),
        migrations.AddIndex(
            model_name='accionista',
            index=models.Index(fields=['nivel'], name='terceros_ac_nivel_1460f6_idx'),
        ),
    ]
