# Generated by Django 5.2.4 on 2025-09-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0029_add_perfil_comercial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tercero',
            name='costosGastos',
        ),
        migrations.RemoveField(
            model_name='tercero',
            name='detalleOtrosIngresos',
        ),
        migrations.RemoveField(
            model_name='tercero',
            name='ingresoMensual',
        ),
        migrations.RemoveField(
            model_name='tercero',
            name='otrosIngresos',
        ),
        migrations.RemoveField(
            model_name='tercero',
            name='totalIngresos',
        ),
    ]
