# Generated by Django 5.2.5 on 2025-08-27 00:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros', '0008_actividadadministrativa_historialestado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tercero_asignado', models.BooleanField(default=True, verbose_name='Tercero Asignado')),
                ('tercero_aprobado', models.BooleanField(default=True, verbose_name='Tercero Aprobado')),
                ('tercero_rechazado', models.BooleanField(default=True, verbose_name='Tercero Rechazado')),
                ('documento_subido', models.BooleanField(default=True, verbose_name='Documento Subido')),
                ('revision_requerida', models.BooleanField(default=True, verbose_name='Revisión Requerida')),
                ('estado_cambiado', models.BooleanField(default=True, verbose_name='Estado Cambiado')),
                ('alerta_cumplimiento', models.BooleanField(default=True, verbose_name='Alerta de Cumplimiento')),
                ('sistema', models.BooleanField(default=True, verbose_name='Notificaciones del Sistema')),
                ('recordatorio', models.BooleanField(default=True, verbose_name='Recordatorios')),
                ('usuario_creado', models.BooleanField(default=False, verbose_name='Usuario Creado')),
                ('rol_cambiado', models.BooleanField(default=True, verbose_name='Rol Cambiado')),
                ('notificaciones_email', models.BooleanField(default=True, verbose_name='Recibir por Email')),
                ('notificaciones_push', models.BooleanField(default=True, verbose_name='Notificaciones Push')),
                ('notificaciones_en_app', models.BooleanField(default=True, verbose_name='Notificaciones en la App')),
                ('horario_inicio', models.TimeField(default='08:00', help_text='Hora de inicio para recibir notificaciones', verbose_name='Horario de Inicio')),
                ('horario_fin', models.TimeField(default='18:00', help_text='Hora límite para recibir notificaciones', verbose_name='Horario de Fin')),
                ('resumen_diario', models.BooleanField(default=False, help_text='Recibir resumen diario de actividades', verbose_name='Resumen Diario')),
                ('resumen_semanal', models.BooleanField(default=False, help_text='Recibir resumen semanal de actividades', verbose_name='Resumen Semanal')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencias de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('tercero_asignado', 'Tercero Asignado'), ('tercero_aprobado', 'Tercero Aprobado'), ('tercero_rechazado', 'Tercero Rechazado'), ('documento_subido', 'Documento Subido'), ('revision_requerida', 'Revisión Requerida'), ('estado_cambiado', 'Estado Cambiado'), ('alerta_cumplimiento', 'Alerta de Cumplimiento'), ('sistema', 'Notificación del Sistema'), ('recordatorio', 'Recordatorio'), ('usuario_creado', 'Usuario Creado'), ('rol_cambiado', 'Rol Cambiado')], max_length=50, verbose_name='Tipo de Notificación')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='Prioridad')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_leida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('datos_extra', models.JSONField(blank=True, help_text='Información adicional en formato JSON', null=True, verbose_name='Datos Adicionales')),
                ('url_accion', models.URLField(blank=True, help_text='URL para redirigir cuando se haga clic en la notificación', verbose_name='URL de Acción')),
                ('tercero_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='terceros.tercero', verbose_name='Tercero Relacionado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('usuario_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_generadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Generó la Notificación')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificatio_usuario_8e0ccb_idx'), models.Index(fields=['tipo', 'fecha_creacion'], name='notificatio_tipo_a93839_idx'), models.Index(fields=['prioridad', 'fecha_creacion'], name='notificatio_priorid_cf2770_idx'), models.Index(fields=['tercero_relacionado'], name='notificatio_tercero_053f32_idx')],
            },
        ),
    ]
