# Generated by Django 5.2.5 on 2025-08-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='url_accion',
            field=models.URLField(blank=True, help_text='URL para redirigir cuando se haga clic en la notificación', null=True, verbose_name='URL de Acción'),
        ),
    ]
